pipeline:
  build-and-push:
    image: plugins/docker
    repo: phpdrone/composer-sa-checker
    tags:
      - latest
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    when:
      branch: release/*
